name: Booth.pm to Discord

on:
  schedule:
    - cron: "0 * * * *"  # runs every hour
  workflow_dispatch:     # lets you run manually

jobs:
  post-items:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run script
        run: python booth_to_discord.py
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
