name: Booth.pm to Discord

on:
  workflow_dispatch:   # manual trigger
  schedule:
    - cron: "0 * * * *"  # runs every hour

jobs:
  post-items:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Find and run Python script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          echo "DEBUG: Looking for Python file..."
          FILE=$(find . -maxdepth 1 -name "*.py" | head -n 1)
          echo "DEBUG: Found $FILE"
          python "$FILE"
